#ifndef ARDUINO_MAIN_PLAIN_CCODE_H
#define ARDUINO_MAIN_PLAIN_CCODE_H

static const char *arduino_pong_code =
    "import math\n"
    "import sys\n"
    "\n"
    "OLED_OUTPUT = True\n"
    "\n"
    "ASCII_DEBUG = False\n"
    "\n"
    "if OLED_OUTPUT:\n"
    "    import ssd1306\n"
    "    from machine import I2C, Pin\n"
    "    SCL_PIN = 22\n"
    "    SDA_PIN = 21\n"
    "LCD_WIDTH = 128\n"
    "LCD_HEIGHT = 64\n"
    "\n"
    "if OLED_OUTPUT:\n"
    "    i2c = I2C(0, scl=Pin(SCL_PIN), sda=Pin(SDA_PIN))\n"
    "    oled = ssd1306.SSD1306_I2C(LCD_WIDTH, LCD_HEIGHT, i2c)\n"
    "else:\n"
    "    oled = None\n"
    "\n"
    "PADDLE_WIDTH = 4\n"
    "PADDLE_HEIGHT = 14\n"
    "PADDLE_BORDER = PADDLE_WIDTH // 2 + 3\n"
    "PADDLE_SPEED = 80\n"
    "PADDLE_AUTO_SPEED = 55\n"
    "\n"
    "PUCK_START_SPEED = 40\n"
    "PUCK_PLAY_SPEED = 120\n"
    "PUCK_RADIUS = 2\n"
    "\n"
    "MAX_DT = 0.05\n"
    "\n"
    "COLLISION_TOLERANCE = 3\n"
    "\n"
    "def _sign(val):\n"
    "    if val > 0:\n"
    "        return 1\n"
    "    if val < 0:\n"
    "        return -1\n"
    "    return 0\n"
    "\n"
    "def _fill_rect_centered(x, y, w, h, color=1):\n"
    "    ox = int(x - w / 2)\n"
    "    oy = int(y - h / 2)\n"
    "    x0 = max(0, ox)\n"
    "    y0 = max(0, oy)\n"
    "    rw = min(int(w), LCD_WIDTH - x0)\n"
    "    rh = min(int(h), LCD_HEIGHT - y0)\n"
    "    if rw > 0 and rh > 0:\n"
    "        if OLED_OUTPUT:\n"
    "            oled.fill_rect(x0, y0, rw, rh, color)\n"
    "\n"
    "def _random_puck_velocity():\n"
    "    global _PUCK_VEL_IDX\n"
    "    vx, vy = _PUCK_VELOCITIES[_PUCK_VEL_IDX % len(_PUCK_VELOCITIES)]\n"
    "    _PUCK_VEL_IDX += 1\n"
    "    return vx, vy\n"
    "\n"
    "_PUCK_VELOCITIES = [\n"
    "    ( 0.299777,  0.278854),\n"
    "    (-0.723800, -0.510216),\n"
    "    (-1.299285,  0.353399),\n"
    "    (-0.198242,  0.180985),\n"
    "    (-1.415851, -0.562724),\n"
    "    ( 0.385606,  0.122490),\n"
    "    (-1.547527, -0.559119),\n"
    "    ( 0.765541,  0.517615),\n"
    "    ( 0.468526, -0.319499),\n"
    "    ( 1.702367, -0.795579),\n"
    "    (-1.953737,  0.694989),\n"
    "    ( 1.198595,  0.459464),\n"
    "    ( 1.583319, -0.842400),\n"
    "    (-0.481705,  0.154704),\n"
    "    (-1.070532,  0.322527),\n"
    "    ( 2.557897,  0.710635),\n"
    "    ( 1.290885, -0.444053),\n"
    "    ( 1.393786, -0.674692),\n"
    "    (-1.231363,  0.403641),\n"
    "    (-0.330321,  0.218262),\n"
    "    (-1.439538, -0.673195),\n"
    "    (-1.302843,  0.369229),\n"
    "    ( 0.594090, -0.541904),\n"
    "    ( 0.236921, -0.197670),\n"
    "    ( 1.435542, -0.574747),\n"
    "    ( 1.013453, -0.714257),\n"
    "    ( 1.129002,  0.494028),\n"
    "    (-1.101814, -0.276007),\n"
    "    (-0.024249,  0.019053),\n"
    "    (-1.053354,  0.722206),\n"
    "    (-1.323984,  0.584159),\n"
    "    ( 0.642460, -0.230465),\n"
    "    (-0.227863,  0.058229),\n"
    "    ( 0.484477,  0.360567),\n"
    "    ( 1.085422,  0.537197),\n"
    "    ( 0.308061, -0.130469),\n"
    "    (-3.101142,  0.943776),\n"
    "    (-1.404513,  0.741037),\n"
    "    (-2.282604, -0.694321),\n"
    "    (-0.487959,  0.197889),\n"
    "    ( 3.120547,  0.858197),\n"
    "    (-0.897647, -0.521095),\n"
    "    (-2.036904, -0.828693),\n"
    "    (-2.483721,  0.955969),\n"
    "    (-1.802931, -0.743217),\n"
    "    ( 1.699721, -0.469887),\n"
    "    (-3.516844,  0.928726),\n"
    "    ( 0.935688,  0.425898),\n"
    "    (-0.316027, -0.123800),\n"
    "    (-0.601032, -0.504189),\n"
    "]\n"
    "_PUCK_VEL_IDX = 0\n"
    "\n"
    "_ASCII_COLS = 64\n"
    "_ASCII_ROWS = 16\n"
    "\n"
    "def _debug_print_frame(left, right, puck):\n"
    "    def _to_col(px):\n"
    "        return min(_ASCII_COLS - 1, max(0, int(px * _ASCII_COLS / LCD_WIDTH)))\n"
    "\n"
    "    def _to_row(py):\n"
    "        return min(_ASCII_ROWS - 1, max(0, int(py * _ASCII_ROWS / LCD_HEIGHT)))\n"
    "\n"
    "    grid = [[' '] * _ASCII_COLS for _ in range(_ASCII_ROWS)]\n"
    "\n"
    "    cx = _ASCII_COLS // 2\n"
    "    for r in range(_ASCII_ROWS):\n"
    "        grid[r][cx] = ':' if r % 2 == 0 else ' '\n"
    "\n"
    "    paddle_half = max(1, int(PADDLE_HEIGHT * _ASCII_ROWS / LCD_HEIGHT / 2))\n"
    "\n"
    "    lx = _to_col(left.position.x)\n"
    "    ly = _to_row(left.position.y)\n"
    "    for r in range(max(0, ly - paddle_half), min(_ASCII_ROWS, ly + paddle_half + 1)):\n"
    "        grid[r][lx] = '|'\n"
    "\n"
    "    rx = _to_col(right.position.x)\n"
    "    ry = _to_row(right.position.y)\n"
    "    for r in range(max(0, ry - paddle_half), min(_ASCII_ROWS, ry + paddle_half + 1)):\n"
    "        grid[r][rx] = '|'\n"
    "\n"
    "    bx = _to_col(puck.position.x)\n"
    "    by = _to_row(puck.position.y)\n"
    "    grid[by][bx] = 'o'\n"
    "\n"
    "    border = '+' + '-' * _ASCII_COLS + '+'\n"
    "    _SCORE_INDENT = 4\n"
    "    _SCORE_GAP = 7\n"
    "    pad = _ASCII_COLS // 2 - _SCORE_INDENT\n"
    "    score_line = (' ' * pad + str(left.score)\n"
    "                  + ' ' * _SCORE_GAP\n"
    "                  + str(right.score))\n"
    "    rows = ['\\x1b[H',\n"
    "            score_line,\n"
    "            border]\n"
    "    for row in grid:\n"
    "        rows.append('|' + ''.join(row) + '|')\n"
    "    rows.append(border)\n"
    "\n"
    "    sys.stdout.write('\\n'.join(rows) + '\\n')\n"
    "\n"
    "class Vector:\n"
    "\n"
    "    __slots__ = (\"x\", \"y\", \"magnitude\", \"angle\")\n"
    "\n"
    "    def __init__(self, x=0.0, y=0.0):\n"
    "        self.x = float(x)\n"
    "        self.y = float(y)\n"
    "        self.magnitude = 0.0\n"
    "        self.angle = 0.0\n"
    "        self._recalc()\n"
    "\n"
    "    def _recalc(self):\n"
    "        self.magnitude = math.sqrt(self.x * self.x + self.y * self.y)\n"
    "        self.angle = math.atan2(self.y, self.x) if self.magnitude else 0.0\n"
    "\n"
    "    def set(self, x, y):\n"
    "        self.x, self.y = float(x), float(y)\n"
    "        self._recalc()\n"
    "        return self\n"
    "\n"
    "    def set_magnitude(self, mag):\n"
    "        if self.magnitude:\n"
    "            scale = float(mag) / self.magnitude\n"
    "            self.x *= scale\n"
    "            self.y *= scale\n"
    "        self.magnitude = float(mag)\n"
    "        return self\n"
    "\n"
    "    def set_angle(self, angle):\n"
    "        self.x = self.magnitude * math.cos(angle)\n"
    "        self.y = self.magnitude * math.sin(angle)\n"
    "        self.angle = float(angle)\n"
    "        return self\n"
    "\n"
    "    def __iadd__(self, other):\n"
    "        self.x += other.x\n"
    "        self.y += other.y\n"
    "        self._recalc()\n"
    "        return self\n"
    "\n"
    "    def __mul__(self, scalar):\n"
    "        return Vector(self.x * scalar, self.y * scalar)\n"
    "\n"
    "    def flip_y(self):\n"
    "        self.y *= -1\n"
    "        self._recalc()\n"
    "        return self\n"
    "\n"
    "    def flip_x(self):\n"
    "        self.x *= -1\n"
    "        self._recalc()\n"
    "        return self\n"
    "\n"
    "class Paddle:\n"
    "\n"
    "    def __init__(self, x):\n"
    "        self.position = Vector(x, LCD_HEIGHT / 2)\n"
    "        self.speed = PADDLE_SPEED\n"
    "        self.score = 0\n"
    "        self.is_auto = False\n"
    "        self._up = False\n"
    "        self._down = False\n"
    "\n"
    "    def set_input(self, up: bool, down: bool):\n"
    "        self._up = up\n"
    "        self._down = down\n"
    "\n"
    "    def update(self, dt, puck):\n"
    "        if self.is_auto:\n"
    "            self.speed = PADDLE_AUTO_SPEED\n"
    "            if _sign(self.position.x - puck.position.x) == _sign(puck.velocity.x):\n"
    "                diff = puck.position.y - self.position.y\n"
    "                if diff < -self.speed * dt:\n"
    "                    self.position.y -= self.speed * dt\n"
    "                elif diff > self.speed * dt:\n"
    "                    self.position.y += self.speed * dt\n"
    "        else:\n"
    "            direction = -1 if self._up else (1 if self._down else 0)\n"
    "            self.position.y += self.speed * dt * direction\n"
    "\n"
    "        half_h = PADDLE_HEIGHT / 2\n"
    "        self.position.y = max(half_h, min(LCD_HEIGHT - half_h, self.position.y))\n"
    "\n"
    "    def show(self):\n"
    "        _fill_rect_centered(self.position.x, self.position.y,\n"
    "                            PADDLE_WIDTH, PADDLE_HEIGHT)\n"
    "\n"
    "class Puck:\n"
    "\n"
    "    def __init__(self, left: Paddle, right: Paddle):\n"
    "        self.position = Vector()\n"
    "        self.velocity = Vector()\n"
    "        self.left = left\n"
    "        self.right = right\n"
    "        self.reset(0)\n"
    "\n"
    "    def reset(self, state: int):\n"
    "        if state > 0:\n"
    "            self.right.score += 1\n"
    "        elif state < 0:\n"
    "            self.left.score += 1\n"
    "\n"
    "        self.position.set(LCD_WIDTH / 2, LCD_HEIGHT / 2)\n"
    "        self.velocity.set(*_random_puck_velocity())\n"
    "        self.velocity.set_magnitude(PUCK_START_SPEED)\n"
    "\n"
    "    def update(self, dt: float):\n"
    "        self.position += self.velocity * dt\n"
    "        self._collide()\n"
    "        self._bounce()\n"
    "        self._score()\n"
    "\n"
    "    def show(self):\n"
    "        size = PUCK_RADIUS * 2\n"
    "        _fill_rect_centered(self.position.x, self.position.y, size, size)\n"
    "\n"
    "    def _score(self):\n"
    "        if self.position.x > LCD_WIDTH + PUCK_RADIUS:\n"
    "            self.reset(-1)\n"
    "        elif self.position.x < -PUCK_RADIUS:\n"
    "            self.reset(1)\n"
    "\n"
    "    def _bounce(self):\n"
    "        if (self.position.y < PUCK_RADIUS or\n"
    "                self.position.y > LCD_HEIGHT - PUCK_RADIUS):\n"
    "            self.velocity.flip_y()\n"
    "\n"
    "    def _collide(self):\n"
    "        half_w = PADDLE_WIDTH / 2\n"
    "        half_h = PADDLE_HEIGHT / 2\n"
    "\n"
    "        on_left = self.position.x - PUCK_RADIUS < self.left.position.x + half_w\n"
    "        on_right = self.position.x + PUCK_RADIUS > self.right.position.x - half_w\n"
    "\n"
    "        if on_left and self._between_paddle(self.left.position):\n"
    "            angle = ((self.position.y - (self.left.position.y - half_h))\n"
    "                     / PADDLE_HEIGHT * math.pi / 2 - math.pi / 4)\n"
    "            self.velocity.set_angle(angle)\n"
    "            self.velocity.set_magnitude(PUCK_PLAY_SPEED)\n"
    "\n"
    "        if on_right and self._between_paddle(self.right.position):\n"
    "            angle = ((self.position.y - (self.right.position.y - half_h))\n"
    "                     / PADDLE_HEIGHT * math.pi / 2 - math.pi / 4)\n"
    "            self.velocity.set_angle(angle)\n"
    "            self.velocity.flip_x()\n"
    "            self.velocity.set_magnitude(PUCK_PLAY_SPEED)\n"
    "\n"
    "    def _between_paddle(self, paddle_pos) -> bool:\n"
    "        half_h = PADDLE_HEIGHT / 2\n"
    "        return (self.position.y + PUCK_RADIUS + COLLISION_TOLERANCE > paddle_pos.y - half_h and\n"
    "                self.position.y - PUCK_RADIUS - COLLISION_TOLERANCE < paddle_pos.y + half_h)\n"
    "\n"
    "def _draw_center_line():\n"
    "    y = 3\n"
    "    while y < LCD_HEIGHT - 2:\n"
    "        _fill_rect_centered(LCD_WIDTH / 2, y, 2, 2)\n"
    "        y += 4\n"
    "\n"
    "def _show_splash():\n"
    "    if OLED_OUTPUT:\n"
    "        oled.fill(0)\n"
    "        oled.text(\"ArduinoPong\", 18, 2, 1)\n"
    "        oled.text(\"L:Single  R:Multi\", 0, 16, 1)\n"
    "        oled.text(\"Up/Down = Move\", 0, 28, 1)\n"
    "        oled.text(\"q = Quit\", 0, 40, 1)\n"
    "        oled.text(\"By Warren James\", 0, 54, 1)\n"
    "        oled.show()\n"
    "\n"
    "class Game:\n"
    "\n"
    "    _SPLASH = 0\n"
    "    _PLAY   = 1\n"
    "    _QUIT   = 2\n"
    "\n"
    "    def __init__(self):\n"
    "        self.left  = Paddle(PADDLE_BORDER)\n"
    "        self.right = Paddle(LCD_WIDTH - PADDLE_BORDER)\n"
    "        self.puck  = Puck(self.left, self.right)\n"
    "        self._state = self._SPLASH\n"
    "\n"
    "    def show_splash(self):\n"
    "        _show_splash()\n"
    "\n"
    "    def step(self, data: dict, dt: float) -> bool:\n"
    "        if self._state == self._SPLASH:\n"
    "            return self._step_splash(data)\n"
    "        if self._state == self._PLAY:\n"
    "            return self._step_play(data, dt)\n"
    "        return False\n"
    "\n"
    "    def _step_splash(self, data: dict) -> bool:\n"
    "        if data.get(\"quit\"):\n"
    "            self._do_quit()\n"
    "            return False\n"
    "\n"
    "        start = data.get(\"start\", \"\")\n"
    "        if start == \"single\":\n"
    "            self.left.is_auto = True\n"
    "            self._begin_play()\n"
    "        elif start == \"multi\":\n"
    "            self._begin_play()\n"
    "        return True\n"
    "\n"
    "    def _step_play(self, data: dict, dt: float) -> bool:\n"
    "        dt = min(float(dt), MAX_DT)\n"
    "\n"
    "        if data.get(\"quit\"):\n"
    "            self._do_quit()\n"
    "            return False\n"
    "\n"
    "        p1 = data.get(\"player1\", \"none\")\n"
    "        self.left.set_input(p1 == \"up\", p1 == \"down\")\n"
    "\n"
    "        p2 = data.get(\"player2\", \"none\")\n"
    "        self.right.set_input(p2 == \"up\", p2 == \"down\")\n"
    "\n"
    "        self.left.update(dt, self.puck)\n"
    "        self.right.update(dt, self.puck)\n"
    "        self.puck.update(dt)\n"
    "\n"
    "        if OLED_OUTPUT:\n"
    "            oled.fill(0)\n"
    "            _draw_center_line()\n"
    "            self.left.show()\n"
    "            self.right.show()\n"
    "            self.puck.show()\n"
    "            oled.text(str(self.left.score),  LCD_WIDTH // 2 - 12, 2, 1)\n"
    "            oled.text(str(self.right.score), LCD_WIDTH // 2 + 6,  2, 1)\n"
    "            oled.show()\n"
    "\n"
    "        if ASCII_DEBUG:\n"
    "            _debug_print_frame(self.left, self.right, self.puck)\n"
    "\n"
    "        return True\n"
    "\n"
    "    def _begin_play(self):\n"
    "        self._state = self._PLAY\n"
    "\n"
    "    def _do_quit(self):\n"
    "        if OLED_OUTPUT:\n"
    "            oled.fill(0)\n"
    "            oled.show()\n"
    "        self._state = self._QUIT\n"
    "\n"
    "_game = Game()\n"
    "\n"
    "def render_frame(data, dt):\n"
    "    return _game.step(data, dt)\n"
    "\n";

#endif
